service: helloworld # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "Storage"
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

  environment:
    PUT: PSR
    Bucket: !Ref Storage

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: psr
          method: get

resources:
 Resources:
   Storage:
     Type: AWS::S3::Bucket
