service: helloworld # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
      Resource:
        - !GetAtt Table.Arn
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetBucketLocation"
      Resource: 
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "Storage"
              - "/*"
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "Storage"
    
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

  environment:
    Bucket: !Ref Storage
    Table: !Ref Table

functions:
  upload:
    handler: handler.upload
    events:
      - http:
          path: upload
          method: post
  list:
    handler: handler.list
    events:
      - http:
          path: list
          method: get

resources:
  Resources:
    Storage:
      Type: AWS::S3::Bucket
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
